language: c
before_install:
  - sudo apt-get install libcurl4-gnutls-dev -qq
  - git clone https://github.com/clibs/clib.git /tmp/clib
  - sudo make -C /tmp/clib install
install: clib install stephenmathieson/describe.h
compiler:
  - clang
  - gcc
script: make test
